/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRadiosRouteImport } from './routes/_app.radios'
import { Route as AppChavesRouteImport } from './routes/_app.chaves'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRadiosRoute = AppRadiosRouteImport.update({
  id: '/radios',
  path: '/radios',
  getParentRoute: () => AppRoute,
} as any)
const AppChavesRoute = AppChavesRouteImport.update({
  id: '/chaves',
  path: '/chaves',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chaves': typeof AppChavesRoute
  '/radios': typeof AppRadiosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chaves': typeof AppChavesRoute
  '/radios': typeof AppRadiosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/chaves': typeof AppChavesRoute
  '/_app/radios': typeof AppRadiosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/chaves' | '/radios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/chaves' | '/radios'
  id: '__root__' | '/' | '/_app' | '/login' | '/_app/chaves' | '/_app/radios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/radios': {
      id: '/_app/radios'
      path: '/radios'
      fullPath: '/radios'
      preLoaderRoute: typeof AppRadiosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chaves': {
      id: '/_app/chaves'
      path: '/chaves'
      fullPath: '/chaves'
      preLoaderRoute: typeof AppChavesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChavesRoute: typeof AppChavesRoute
  AppRadiosRoute: typeof AppRadiosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChavesRoute: AppChavesRoute,
  AppRadiosRoute: AppRadiosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
